[package]
name = "ezark"
version = "1.1.0"
edition = "2021"
authors = ["ryzeon-dev"]
repository = "https://github.com/ryzeon-dev/ezark"
license = "AGPL-3.0-or-later"
description = "Open source archive utility written in Rust"
readme = "README.md"

[dependencies]
rsjson = "0.5.1"